# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nn.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nn.proto',
  package='nn',
  serialized_pb='\n\x08nn.proto\x12\x02nn\"\x95\x02\n\x0eLearningParams\x12\x15\n\x05l1_wt\x18\x01 \x02(\x02:\x06\x30.0001\x12\x15\n\x05l2_wt\x18\x02 \x02(\x02:\x06\x30.0001\x12\x16\n\x07\x65psilon\x18\x03 \x02(\x02:\x05\x30.001\x12!\n\x13\x65psilon_anneal_rate\x18\x04 \x02(\x02:\x04\x30.99\x12\x15\n\x08momentum\x18\x05 \x02(\x02:\x03\x30.9\x12\x16\n\x0bstart_epoch\x18\x06 \x02(\x05:\x01\x30\x12\x19\n\tend_epoch\x18\x07 \x02(\x05:\x06\x31\x30\x30\x30\x30\x30\x12\x17\n\x0c\x64ropout_rate\x18\x08 \x02(\x02:\x01\x30\x12\x1d\n\x12wt_norm_constraint\x18\t \x02(\x02:\x01\x30\x12\x18\n\nada_lambda\x18\n \x02(\x02:\x04\x30.95\"Q\n\nInitParams\x12\x13\n\x08wt_sigma\x18\x01 \x02(\x02:\x01\x33\x12\x16\n\nbiases_min\x18\x02 \x02(\x02:\x02-5\x12\x16\n\nbiases_max\x18\x03 \x02(\x02:\x02-3\"\x99\x02\n\x05Layer\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\tinput_dim\x18\x02 \x02(\x05\x12\x11\n\tnum_units\x18\x03 \x02(\x05\x12!\n\x04type\x18\x04 \x02(\x0e\x32\x13.nn.Layer.LayerType\x12#\n\x0binit_params\x18\x05 \x02(\x0b\x32\x0e.nn.InitParams\x12-\n\x11learning_schedule\x18\x06 \x03(\x0b\x32\x12.nn.LearningParams\x12\x15\n\rnum_softmaxes\x18\x07 \x01(\x05\"N\n\tLayerType\x12\n\n\x06LINEAR\x10\x00\x12\x0b\n\x07SIGMOID\x10\x01\x12\x08\n\x04RELU\x10\x02\x12\x0b\n\x07SOFTMAX\x10\x03\x12\x11\n\rMULTI_SOFTMAX\x10\x04\"\x1f\n\x02nn\x12\x19\n\x06layers\x18\x01 \x03(\x0b\x32\t.nn.Layer')



_LAYER_LAYERTYPE = _descriptor.EnumDescriptor(
  name='LayerType',
  full_name='nn.Layer.LayerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LINEAR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGMOID', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELU', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTMAX', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTI_SOFTMAX', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=583,
  serialized_end=661,
)


_LEARNINGPARAMS = _descriptor.Descriptor(
  name='LearningParams',
  full_name='nn.LearningParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='l1_wt', full_name='nn.LearningParams.l1_wt', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.0001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_wt', full_name='nn.LearningParams.l2_wt', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.0001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='nn.LearningParams.epsilon', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epsilon_anneal_rate', full_name='nn.LearningParams.epsilon_anneal_rate', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.99,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momentum', full_name='nn.LearningParams.momentum', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.9,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_epoch', full_name='nn.LearningParams.start_epoch', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_epoch', full_name='nn.LearningParams.end_epoch', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=100000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout_rate', full_name='nn.LearningParams.dropout_rate', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wt_norm_constraint', full_name='nn.LearningParams.wt_norm_constraint', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ada_lambda', full_name='nn.LearningParams.ada_lambda', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.95,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=294,
)


_INITPARAMS = _descriptor.Descriptor(
  name='InitParams',
  full_name='nn.InitParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wt_sigma', full_name='nn.InitParams.wt_sigma', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='biases_min', full_name='nn.InitParams.biases_min', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=-5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='biases_max', full_name='nn.InitParams.biases_max', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=-3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=296,
  serialized_end=377,
)


_LAYER = _descriptor.Descriptor(
  name='Layer',
  full_name='nn.Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='nn.Layer.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_dim', full_name='nn.Layer.input_dim', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_units', full_name='nn.Layer.num_units', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='nn.Layer.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_params', full_name='nn.Layer.init_params', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_schedule', full_name='nn.Layer.learning_schedule', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_softmaxes', full_name='nn.Layer.num_softmaxes', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LAYER_LAYERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=380,
  serialized_end=661,
)


_NN = _descriptor.Descriptor(
  name='nn',
  full_name='nn.nn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layers', full_name='nn.nn.layers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=663,
  serialized_end=694,
)

_LAYER.fields_by_name['type'].enum_type = _LAYER_LAYERTYPE
_LAYER.fields_by_name['init_params'].message_type = _INITPARAMS
_LAYER.fields_by_name['learning_schedule'].message_type = _LEARNINGPARAMS
_LAYER_LAYERTYPE.containing_type = _LAYER;
_NN.fields_by_name['layers'].message_type = _LAYER
DESCRIPTOR.message_types_by_name['LearningParams'] = _LEARNINGPARAMS
DESCRIPTOR.message_types_by_name['InitParams'] = _INITPARAMS
DESCRIPTOR.message_types_by_name['Layer'] = _LAYER
DESCRIPTOR.message_types_by_name['nn'] = _NN

class LearningParams(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEARNINGPARAMS

  # @@protoc_insertion_point(class_scope:nn.LearningParams)

class InitParams(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITPARAMS

  # @@protoc_insertion_point(class_scope:nn.InitParams)

class Layer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAYER

  # @@protoc_insertion_point(class_scope:nn.Layer)

class nn(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NN

  # @@protoc_insertion_point(class_scope:nn.nn)


# @@protoc_insertion_point(module_scope)
