# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: run_params.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='run_params.proto',
  package='run_params',
  serialized_pb='\n\x10run_params.proto\x12\nrun_params\"\xa1\x02\n\nDataParams\x12\x17\n\tuse_delta\x18\x01 \x02(\x08:\x04true\x12\x45\n\rnormalization\x18\x02 \x02(\x0e\x32(.run_params.DataParams.NormalizationType:\x04\x43MVN\x12\x1d\n\x11num_frames_per_pt\x18\x03 \x02(\x05:\x02\x31\x35\x12$\n\x18num_output_frames_per_pt\x18\x04 \x01(\x05:\x02\x31\x35\x12 \n\x11smooth_alignments\x18\x05 \x01(\x08:\x05\x66\x61lse\"L\n\x11NormalizationType\x12\x07\n\x03\x43MN\x10\x00\x12\x08\n\x04\x43MVN\x10\x01\x12\x12\n\x0eGLOB_NORMALIZE\x10\x02\x12\x10\n\x0cNO_NORMALIZE\x10\x03\"\x82\x01\n\x06params\x12+\n\x0b\x64\x61ta_params\x18\x01 \x02(\x0b\x32\x16.run_params.DataParams\x12\x17\n\nbatch_size\x18\x02 \x02(\x05:\x03\x31\x32\x38\x12\x1a\n\x0emax_bad_epochs\x18\x03 \x02(\x05:\x02\x31\x30\x12\x16\n\nmax_epochs\x18\x04 \x02(\x05:\x02\x34\x30')



_DATAPARAMS_NORMALIZATIONTYPE = _descriptor.EnumDescriptor(
  name='NormalizationType',
  full_name='run_params.DataParams.NormalizationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMVN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GLOB_NORMALIZE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_NORMALIZE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=246,
  serialized_end=322,
)


_DATAPARAMS = _descriptor.Descriptor(
  name='DataParams',
  full_name='run_params.DataParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_delta', full_name='run_params.DataParams.use_delta', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normalization', full_name='run_params.DataParams.normalization', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_frames_per_pt', full_name='run_params.DataParams.num_frames_per_pt', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_output_frames_per_pt', full_name='run_params.DataParams.num_output_frames_per_pt', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='smooth_alignments', full_name='run_params.DataParams.smooth_alignments', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DATAPARAMS_NORMALIZATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=322,
)


_PARAMS = _descriptor.Descriptor(
  name='params',
  full_name='run_params.params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_params', full_name='run_params.params.data_params', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='run_params.params.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=128,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_bad_epochs', full_name='run_params.params.max_bad_epochs', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_epochs', full_name='run_params.params.max_epochs', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=40,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=325,
  serialized_end=455,
)

_DATAPARAMS.fields_by_name['normalization'].enum_type = _DATAPARAMS_NORMALIZATIONTYPE
_DATAPARAMS_NORMALIZATIONTYPE.containing_type = _DATAPARAMS;
_PARAMS.fields_by_name['data_params'].message_type = _DATAPARAMS
DESCRIPTOR.message_types_by_name['DataParams'] = _DATAPARAMS
DESCRIPTOR.message_types_by_name['params'] = _PARAMS

class DataParams(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATAPARAMS

  # @@protoc_insertion_point(class_scope:run_params.DataParams)

class params(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAMS

  # @@protoc_insertion_point(class_scope:run_params.params)


# @@protoc_insertion_point(module_scope)
