# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='dbn.proto',
  package='dbn',
  serialized_pb='\n\tdbn.proto\x12\x03\x64\x62n\"\x9c\x03\n\x0bLayerConfig\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\tinput_dim\x18\x02 \x02(\x05\x12\x11\n\tnum_units\x18\x03 \x02(\x05\x12(\n\x04type\x18\x04 \x02(\x0e\x32\x1a.dbn.LayerConfig.LayerType\x12\x13\n\x08wt_sigma\x18\x05 \x02(\x02:\x01\x33\x12\x13\n\x08vis_bias\x18\x06 \x02(\x02:\x01\x30\x12\x14\n\x08hid_bias\x18\x07 \x02(\x02:\x02-1\x12\x19\n\tepsilon_w\x18\x08 \x02(\x02:\x06\x30.0001\x12\x19\n\tepsilon_b\x18\t \x02(\x02:\x06\x30.0001\x12\x1d\n\x10initial_momentum\x18\n \x02(\x02:\x03\x30.9\x12\x1b\n\x0e\x66inal_momentum\x18\x0b \x02(\x02:\x03\x30.9\x12\x1b\n\x10mom_switch_epoch\x18\x0c \x02(\x05:\x01\x30\x12\x13\n\x08l2_decay\x18\r \x02(\x02:\x01\x30\x12\x16\n\nnum_epochs\x18\x0e \x02(\x05:\x02\x35\x30\"3\n\tLayerType\x12\x11\n\rBINARY_BINARY\x10\x00\x12\x13\n\x0fGAUSSIAN_BINARY\x10\x01\".\n\x03\x64\x62n\x12\'\n\rlayer_configs\x18\x01 \x03(\x0b\x32\x10.dbn.LayerConfig')



_LAYERCONFIG_LAYERTYPE = descriptor.EnumDescriptor(
  name='LayerType',
  full_name='dbn.LayerConfig.LayerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='BINARY_BINARY', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAUSSIAN_BINARY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=380,
  serialized_end=431,
)


_LAYERCONFIG = descriptor.Descriptor(
  name='LayerConfig',
  full_name='dbn.LayerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='dbn.LayerConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='input_dim', full_name='dbn.LayerConfig.input_dim', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_units', full_name='dbn.LayerConfig.num_units', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='dbn.LayerConfig.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wt_sigma', full_name='dbn.LayerConfig.wt_sigma', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vis_bias', full_name='dbn.LayerConfig.vis_bias', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hid_bias', full_name='dbn.LayerConfig.hid_bias', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='epsilon_w', full_name='dbn.LayerConfig.epsilon_w', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.0001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='epsilon_b', full_name='dbn.LayerConfig.epsilon_b', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.0001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initial_momentum', full_name='dbn.LayerConfig.initial_momentum', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.9,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='final_momentum', full_name='dbn.LayerConfig.final_momentum', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.9,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mom_switch_epoch', full_name='dbn.LayerConfig.mom_switch_epoch', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='l2_decay', full_name='dbn.LayerConfig.l2_decay', index=12,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_epochs', full_name='dbn.LayerConfig.num_epochs', index=13,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=50,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LAYERCONFIG_LAYERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=431,
)


_DBN = descriptor.Descriptor(
  name='dbn',
  full_name='dbn.dbn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='layer_configs', full_name='dbn.dbn.layer_configs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=433,
  serialized_end=479,
)

_LAYERCONFIG.fields_by_name['type'].enum_type = _LAYERCONFIG_LAYERTYPE
_LAYERCONFIG_LAYERTYPE.containing_type = _LAYERCONFIG;
_DBN.fields_by_name['layer_configs'].message_type = _LAYERCONFIG
DESCRIPTOR.message_types_by_name['LayerConfig'] = _LAYERCONFIG
DESCRIPTOR.message_types_by_name['dbn'] = _DBN

class LayerConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAYERCONFIG
  
  # @@protoc_insertion_point(class_scope:dbn.LayerConfig)

class dbn(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DBN
  
  # @@protoc_insertion_point(class_scope:dbn.dbn)

# @@protoc_insertion_point(module_scope)
